#!/usr/bin/env bash
# Agent execution logic for Milhouse
# Handles PRD processing, archiving, progress tracking, and agent iteration loop

# Track child PID for cleanup
MILHOUSE_AGENT_PID=""

_milhouse_cleanup() {
    echo ""
    echo "Milhouse interrupted. Cleaning up..."
    if [[ -n "$MILHOUSE_AGENT_PID" ]] && kill -0 "$MILHOUSE_AGENT_PID" 2>/dev/null; then
        kill "$MILHOUSE_AGENT_PID" 2>/dev/null
        wait "$MILHOUSE_AGENT_PID" 2>/dev/null
    fi
    echo "Stopped."
    exit 130
}

get_dev_folder() {
    local config_file="${MILHOUSE_CONFIG:-$HOME/.config/milhouse/config}"
    if [[ -f "$config_file" ]]; then
        local dev_folder=$(grep "^dev_folder=" "$config_file" 2>/dev/null | cut -d'=' -f2- | tr -d '"' | tr -d "'")
        if [[ -n "$dev_folder" ]]; then
            echo "$dev_folder"
            return 0
        fi
    fi
    echo "${DEFAULT_DEV_FOLDER:-$HOME/dev}"
}

find_available_projects() {
    local dev_folder=$(get_dev_folder)
    local -a projects=()
    if [[ -d "$dev_folder" ]]; then
        while IFS= read -r -d '' prd_file; do
            local milhouse_dir=$(dirname "$prd_file")
            local project_dir=$(dirname "$milhouse_dir")
            local project_name=$(basename "$project_dir")
            if [[ "$project_name" == "archive" ]]; then
                continue
            fi
            local exists=false
            if [[ ${#projects[@]} -gt 0 ]]; then
                for p in "${projects[@]}"; do
                    if [[ "$p" == "$project_name" ]]; then
                        exists=true
                        break
                    fi
                done
            fi
            if [[ "$exists" == false ]]; then
                projects+=("$project_name")
            fi
        done < <(find "$dev_folder" -name "prd.json" -path "*/.milhouse/*" -print0 2>/dev/null)
    fi
    if [[ ${#projects[@]} -gt 0 ]]; then
        printf '%s\n' "${projects[@]}"
    fi
}

get_simple_prompt() {
    # Point tools at the bundled prompt path from the Milhouse install.
    local prompt_file="${MILHOUSE_REPO_DIR:-}/prompt.md"
    if [[ ! -f "$prompt_file" ]]; then
        prompt_file=".milhouse/prompt.md"
    fi

    echo "You are Milhouse, an autonomous AI agent. Read and follow the agent instructions in $prompt_file. Your project context is in AGENTS.md at the project root (fallback: legacy CLAUDE.md). Follow the workflow: read prd.json, pick one incomplete story, implement it, run quality checks, commit, update progress.txt, and signal completion with <promise>COMPLETE</promise> when all stories pass."
}

create_agents_bootstrap_template() {
    local target_file="$1"
    local project_name="$2"

    cat > "$target_file" << 'EOF'
# AGENTS.md (Bootstrap Template)

<!-- MILHOUSE_DUMMY_AGENTS_TEMPLATE -->

This is a starter `AGENTS.md` generated by Milhouse.

## Next Step (Auto-Tailor)

Milhouse should use the selected CLI tool to:
- scan the repository structure and key config files
- read `.milhouse/prd.json` and `.milhouse/progress.txt` (if present)
- replace this file with project-specific instructions
- include concrete run/lint/test/build commands and conventions

## Project

- Name: PROJECT_NAME
- Status: bootstrap
EOF

    sed -i.bak "s/PROJECT_NAME/$project_name/g" "$target_file"
    rm "$target_file.bak" 2>/dev/null || true
}

bootstrap_agents_md() {
    local project_dir="$1"
    local milhouse_dir="$2"
    local tool="$3"
    local timeout_mins="$4"
    local verbose="$5"
    local agents_file="$project_dir/AGENTS.md"
    local project_name
    project_name="$(basename "$project_dir")"

    local needs_bootstrap="false"
    if [[ ! -f "$agents_file" ]]; then
        echo "AGENTS.md not found. Creating bootstrap template..."
        create_agents_bootstrap_template "$agents_file" "$project_name"
        needs_bootstrap="true"
    elif grep -q "MILHOUSE_DUMMY_AGENTS_TEMPLATE" "$agents_file" 2>/dev/null; then
        needs_bootstrap="true"
    fi

    if [[ "$needs_bootstrap" != "true" ]]; then
        return 0
    fi

    local run_func="${tool}_run"
    if ! command -v "$run_func" &> /dev/null; then
        echo "Warning: No adapter found for tool '$tool'. Keeping bootstrap AGENTS.md."
        return 0
    fi

    local bootstrap_prompt
    bootstrap_prompt=$(cat << EOF
Initialize AGENTS.md for this repository.

Working directory: $project_dir
Milhouse directory: $milhouse_dir

Task:
1. Scan this project to infer stack, tooling, and conventions.
2. Read .milhouse/prd.json and .milhouse/progress.txt if available.
3. Rewrite AGENTS.md at the project root with practical, project-specific instructions.
4. Include explicit commands for setup, run, lint, test, and build if discoverable.
5. Remove placeholder/bootstrap text and keep the file concise and actionable.
6. Keep the file in Markdown and preserve the filename AGENTS.md.

Return a brief summary of what you changed and include <promise>AGENTS_BOOTSTRAPPED</promise> when done.
EOF
)

    echo "Bootstrapping AGENTS.md using tool: $tool"
    local tmpfile
    tmpfile=$(mktemp)

    (
        cd "$project_dir" || exit 1
        "$run_func" "$bootstrap_prompt" "$tmpfile" "$timeout_mins" "$verbose"
    )
    local exit_code=$?
    local output
    output="$(cat "$tmpfile" 2>/dev/null || true)"
    rm -f "$tmpfile"

    if [[ $exit_code -ne 0 ]]; then
        echo "Warning: AGENTS.md bootstrap via $tool failed (exit $exit_code). Keeping bootstrap template."
        return 0
    fi

    if ! grep -q "<promise>AGENTS_BOOTSTRAPPED</promise>" <<< "$output"; then
        echo "Note: bootstrap run completed without explicit completion marker."
    fi
}

create_agents_from_legacy_claude() {
    local project_dir="$1"
    local claude_file="$project_dir/CLAUDE.md"
    local agents_file="$project_dir/AGENTS.md"

    if [[ ! -f "$claude_file" ]]; then
        return 1
    fi

    cat > "$agents_file" << 'EOF'
# AGENTS.md

<!-- Generated by Milhouse from legacy CLAUDE.md -->

This file was generated from `CLAUDE.md` for compatibility.
Review and refine these instructions as needed.

EOF

    cat "$claude_file" >> "$agents_file"
    return 0
}

ensure_project_context_file() {
    local project_dir="$1"
    local milhouse_dir="$2"
    local tool="$3"
    local timeout_mins="$4"
    local verbose="$5"

    local agents_file="$project_dir/AGENTS.md"
    local claude_file="$project_dir/CLAUDE.md"

    if [[ -f "$agents_file" ]]; then
        return 0
    fi

    if [[ -f "$claude_file" ]]; then
        echo "Found legacy CLAUDE.md in project root. Creating AGENTS.md for compatibility..."
        create_agents_from_legacy_claude "$project_dir"
    fi

    bootstrap_agents_md "$project_dir" "$milhouse_dir" "$tool" "$timeout_mins" "$verbose"

    if [[ -f "$agents_file" || -f "$claude_file" ]]; then
        return 0
    fi

    echo "Warning: No AGENTS.md or CLAUDE.md found in project root ($project_dir)"
    echo "Milhouse requires AGENTS.md (or legacy CLAUDE.md) in the project root directory."
    return 1
}

milhouse_config() {
    local config_file="${MILHOUSE_CONFIG:-$HOME/.config/milhouse/config}"
    local config_dir="$(dirname "$config_file")"

    case "${1:-}" in
        set)
            local key="$2"
            local value="$3"
            if [[ -z "$key" || -z "$value" ]]; then
                echo "Usage: milhouse config set <key> <value>"
                echo ""
                echo "Available keys:"
                echo "  default_tool    Default AI tool (claude|copilot|opencode|amp|pi|codex)"
                echo "  dev_folder      Dev folder to scan for projects"
                return 1
            fi
            mkdir -p "$config_dir"
            if [[ -f "$config_file" ]] && grep -q "^${key}=" "$config_file" 2>/dev/null; then
                sed -i '' "s|^${key}=.*|${key}=${value}|" "$config_file"
            else
                echo "${key}=${value}" >> "$config_file"
            fi
            echo "Set ${key}=${value}"
            ;;
        edit)
            mkdir -p "$config_dir"
            if [[ ! -f "$config_file" ]]; then
                cat > "$config_file" << 'CONF'
# Milhouse Configuration
# Default AI tool for 'milhouse run' (claude|copilot|opencode|amp|pi|codex)
default_tool=claude

# Dev folder to scan for projects
# dev_folder=~/dev
CONF
                echo "Created default config at $config_file"
            fi
            "${EDITOR:-vi}" "$config_file"
            ;;
        *)
            if [[ -f "$config_file" ]]; then
                echo "Milhouse Configuration ($config_file):"
                echo ""
                cat "$config_file"
            else
                echo "No configuration file found."
                echo ""
                echo "Run 'milhouse config edit' to create one, or:"
                echo "  milhouse config set default_tool copilot"
            fi
            ;;
    esac
}

archive_completed_run() {
    local milhouse_dir="$1"
    local prd_file="$milhouse_dir/prd.json"
    local progress_file="$milhouse_dir/progress.txt"
    local archive_dir="$milhouse_dir/archive"

    if [[ ! -f "$prd_file" ]]; then
        return 0
    fi

    local branch_name=$(jq -r '.branchName // "unknown"' "$prd_file" 2>/dev/null)
    local folder_name=$(echo "$branch_name" | sed 's|^milhouse/||; s|^feature/||')
    local date=$(date +%Y-%m-%d)
    local archive_folder="$archive_dir/$date-$folder_name"

    echo "Archiving completed run: $branch_name"
    mkdir -p "$archive_folder"
    [[ -f "$prd_file" ]] && cp "$prd_file" "$archive_folder/"
    [[ -f "$progress_file" ]] && cp "$progress_file" "$archive_folder/"
    echo "  Archived to: $archive_folder"

    # Delete the original PRD file to prevent re-running
    [[ -f "$prd_file" ]] && rm "$prd_file"
    echo "  Removed completed $prd_file"

    # Reset progress file for next run
    echo "# Milhouse Progress Log" > "$progress_file"
    echo "Last archival: $(date)" >> "$progress_file"
    echo "---" >> "$progress_file"
}

run_agent() {
    # Set up Ctrl+C trap for clean shutdown
    trap _milhouse_cleanup INT TERM

    # Parse arguments
    local turns="25"
    local verbose="true"
    local timeout_mins="15"  # Per-iteration timeout in minutes

    # Read default tool from config, fall back to claude
    local config_file="${MILHOUSE_CONFIG:-$HOME/.config/milhouse/config}"
    local tool="claude"
    if [[ -f "$config_file" ]]; then
        local configured_tool=$(grep "^default_tool=" "$config_file" 2>/dev/null | cut -d'=' -f2- | tr -d '"' | tr -d "'")
        if [[ -n "$configured_tool" ]]; then
            tool="$configured_tool"
        fi
    fi

    while [[ $# -gt 0 ]]; do
        case $1 in
            --tool)
                tool="$2"
                shift 2
                ;;
            --quiet)
                verbose="false"
                shift
                ;;
            --verbose)
                verbose="true"
                shift
                ;;
            --timeout)
                timeout_mins="$2"
                shift 2
                ;;
            [0-9]*)
                turns="$1"
                shift
                ;;
            *)
                shift
                ;;
        esac
    done

    # Validate tool choice
    if [[ "$tool" != "claude" && "$tool" != "copilot" && "$tool" != "opencode" && "$tool" != "amp" && "$tool" != "pi" && "$tool" != "codex" ]]; then
        echo "Error: Invalid tool '$tool'. Must be 'claude', 'copilot', 'opencode', 'amp', 'pi', or 'codex'."
        return 1
    fi

    # Determine project directory
    local PROJECT_DIR=""
    local MILHOUSE_DIR=""

    if [[ "$(basename "$PWD")" == ".milhouse" ]]; then
        MILHOUSE_DIR="$PWD"
        PROJECT_DIR="$(dirname "$PWD")"
    elif [[ -d "$PWD/.milhouse" ]]; then
        MILHOUSE_DIR="$PWD/.milhouse"
        PROJECT_DIR="$PWD"
    elif [[ -f "$PWD/AGENTS.md" || -f "$PWD/CLAUDE.md" ]]; then
        PROJECT_DIR="$PWD"
        if [[ -d "$PWD/.milhouse" ]]; then
            MILHOUSE_DIR="$PWD/.milhouse"
        else
            MILHOUSE_DIR="$PWD"
        fi
    fi

    # Validate .milhouse directory exists
    if [[ -z "$MILHOUSE_DIR" ]] || [[ ! -d "$MILHOUSE_DIR" ]]; then
        local dev_folder=$(get_dev_folder)
        echo "Error: No Milhouse project found in current directory."
        echo ""
        echo "Make sure you're running from either:"
        echo "  - A project directory with a .milhouse/ subdirectory"
        echo "  - A .milhouse/ subdirectory"
        echo ""
        echo "Searching for available projects in $dev_folder..."
        echo ""

        local projects=($(find_available_projects))
        if [[ ${#projects[@]} -gt 0 ]]; then
            echo "Available projects:"
            for project in "${projects[@]}"; do
                echo "  - $project"
            done
            echo ""
            echo "To run milhouse in a project:"
            echo "  cd $dev_folder/<project> && milhouse run"
        else
            echo "No projects found in $dev_folder/"
            echo ""
            echo "To set up a new project:"
            echo "  cd $dev_folder/<your-project>"
            echo "  milhouse install ."
        fi
        return 1
    fi

    # Set up file paths
    local SCRIPT_DIR="$MILHOUSE_DIR"
    local PRD_FILE="$SCRIPT_DIR/prd.json"
    local PROGRESS_FILE="$SCRIPT_DIR/progress.txt"
    local ARCHIVE_DIR="$SCRIPT_DIR/archive"
    local LAST_BRANCH_FILE="$SCRIPT_DIR/.last-branch"

    # Archive previous run if branch changed
    if [ -f "$PRD_FILE" ] && [ -f "$LAST_BRANCH_FILE" ]; then
        CURRENT_BRANCH=$(jq -r '.branchName // empty' "$PRD_FILE" 2>/dev/null || echo "")
        LAST_BRANCH=$(cat "$LAST_BRANCH_FILE" 2>/dev/null || echo "")

        if [ -n "$CURRENT_BRANCH" ] && [ -n "$LAST_BRANCH" ] && [ "$CURRENT_BRANCH" != "$LAST_BRANCH" ]; then
            DATE=$(date +%Y-%m-%d)
            FOLDER_NAME=$(echo "$LAST_BRANCH" | sed 's|^milhouse/||; s|^feature/||')
            ARCHIVE_FOLDER="$ARCHIVE_DIR/$DATE-$FOLDER_NAME"

            echo "Archiving previous run: $LAST_BRANCH"
            mkdir -p "$ARCHIVE_FOLDER"
            [ -f "$PRD_FILE" ] && cp "$PRD_FILE" "$ARCHIVE_FOLDER/"
            [ -f "$PROGRESS_FILE" ] && cp "$PROGRESS_FILE" "$ARCHIVE_FOLDER/"
            echo "   Archived to: $ARCHIVE_FOLDER"

            echo "# Milhouse Progress Log" > "$PROGRESS_FILE"
            echo "Started: $(date)" >> "$PROGRESS_FILE"
            echo "---" >> "$PROGRESS_FILE"
        fi
    fi

    # Track current branch
    if [ -f "$PRD_FILE" ]; then
        CURRENT_BRANCH=$(jq -r '.branchName // empty' "$PRD_FILE" 2>/dev/null || echo "")
        if [ -n "$CURRENT_BRANCH" ]; then
            echo "$CURRENT_BRANCH" > "$LAST_BRANCH_FILE"
        fi
    fi

    # Initialize progress file if it doesn't exist
    if [ ! -f "$PROGRESS_FILE" ]; then
        echo "# Milhouse Progress Log" > "$PROGRESS_FILE"
        echo "Started: $(date)" >> "$PROGRESS_FILE"
        echo "---" >> "$PROGRESS_FILE"
    fi

    # Ensure AGENTS.md/legacy CLAUDE.md context exists; bootstrap AGENTS.md when needed.
    if ! ensure_project_context_file "$PROJECT_DIR" "$MILHOUSE_DIR" "$tool" "$timeout_mins" "$verbose"; then
        return 1
    fi

    # QMD Integration - Search documentation before starting
    local project_dir="$(dirname "$SCRIPT_DIR")"
    local project_name="$(basename "$project_dir")"

    if command -v qmd &> /dev/null && qmd collection list 2>/dev/null | grep -q "^$project_name "; then
        echo "Using qmd collection: $project_name"

        if [ -f "$PRD_FILE" ]; then
            local current_story=$(jq -r '.userStories[] | select(.passes == false) | .title' "$PRD_FILE" 2>/dev/null | head -1)

            if [[ -n "$current_story" ]]; then
                echo "Searching documentation for: $current_story"
                qmd_search_for_story "$current_story" "$project_name"
                echo ""
            fi
        fi
    else
        echo "No qmd collection found for $project_name"
        echo "Run 'milhouse qmd setup' to enable documentation search"
        echo ""
    fi

    # Use simple prompt - Claude reads files itself
    local SIMPLE_PROMPT
    SIMPLE_PROMPT=$(get_simple_prompt)

    echo "Starting Milhouse - Tool: $tool - Max iterations: $turns - Timeout: ${timeout_mins}m/iter"
    echo "Press Ctrl+C to stop at any time."
    echo ""

    local consecutive_failures=0
    local MAX_CONSECUTIVE_FAILURES=3

    # Main agent execution loop
    for i in $(seq 1 $turns); do
        echo ""
        echo "==============================================================="
        echo "  Milhouse Iteration $i of $turns ($tool)"
        echo "  Started: $(date '+%H:%M:%S')  Timeout: ${timeout_mins}m"
        echo "==============================================================="

        # Check if all stories are already complete before running
        if [ -f "$PRD_FILE" ]; then
            local remaining=$(jq '[.userStories[] | select(.passes == false)] | length' "$PRD_FILE" 2>/dev/null)
            if [[ "$remaining" == "0" ]]; then
                echo ""
                echo "All stories in prd.json are complete!"
                archive_completed_run "$MILHOUSE_DIR"
                trap - INT TERM
                return 0
            fi
            echo "  Stories remaining: $remaining"
        fi

        # Create temp file for output capture (allows tee for streaming)
        local tmpfile=$(mktemp)

        local exit_code=0
        # Execute tool adapter
        local run_func="${tool}_run"
        if command -v "$run_func" &> /dev/null; then
             "$run_func" "$SIMPLE_PROMPT" "$tmpfile" "$timeout_mins" "$verbose"
             exit_code=$?
        else
             echo "Error: No adapter found for tool '$tool'"
             # Fallback or error
             exit_code=1
        fi

        OUTPUT=$(cat "$tmpfile")
        rm -f "$tmpfile"

        # Handle timeout (exit code 124)
        if [[ $exit_code -eq 124 ]]; then
            echo ""
            echo "WARNING: Iteration $i timed out after ${timeout_mins} minutes."
            consecutive_failures=$((consecutive_failures + 1))
        # Handle other errors
        elif [[ $exit_code -ne 0 ]]; then
            echo ""
            echo "WARNING: $tool exited with code $exit_code on iteration $i."
            consecutive_failures=$((consecutive_failures + 1))
        else
            consecutive_failures=0
        fi

        # Check for consecutive failures
        if [[ $consecutive_failures -ge $MAX_CONSECUTIVE_FAILURES ]]; then
            echo ""
            echo "ERROR: $MAX_CONSECUTIVE_FAILURES consecutive failures. Stopping."
            echo "Check $PROGRESS_FILE for status."
            trap - INT TERM
            return 1
        fi

        # Check for completion signal
        if echo "$OUTPUT" | grep -q "<promise>COMPLETE</promise>"; then
            echo ""
            echo "Milhouse completed all tasks!"
            echo "Completed at iteration $i of $turns"
            archive_completed_run "$MILHOUSE_DIR"
            trap - INT TERM
            return 0
        fi

        # Check for empty output (agent produced nothing)
        if [[ -z "$OUTPUT" ]]; then
            echo ""
            echo "WARNING: $tool produced no output on iteration $i."
            consecutive_failures=$((consecutive_failures + 1))
        fi

        echo ""
        echo "Iteration $i complete. Continuing in 2s..."

        # Update progress log
        {
            echo "## Iteration $i ($tool)"
            echo "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
            echo "Exit Code: $exit_code"
            if echo "$OUTPUT" | grep -q "<promise>COMPLETE</promise>"; then
                 echo "Status: COMPLETED"
            else
                 echo "Status: In Progress"
            fi
            echo "---"
        } >> "$PROGRESS_FILE"

        sleep 2
    done

    echo ""
    echo "Milhouse reached max iterations ($turns) without completing all tasks."
    echo "Check $PROGRESS_FILE for status."
    trap - INT TERM
    return 1
}
